services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${DB_NAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongo+srv://${DB_NAME}:${DB_PASSWORD}@hotelbooking.q3qxgry.mongodb.net/nest?retryWrites=true&w=majority
    depends_on:
      - mongodb

  backend:
    build: ./hotelBooking_nest_back
    ports:
      - 7000:7000
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongodb

  frontend:
    build: ./hotelBooking_react_front
    ports:
      - 3000:3000
    environment:
      - CLIENT_PORT=${CLIENT_PORT}